// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SportActivityAPI.Repository.Models
{
    public partial class Activitytype
    {
        public Activitytype()
        {
            Activity = new HashSet<Activity>();
            UserHasTarget = new HashSet<UserHasTarget>();
        }

        public int Id { get; set; }
        public string Name { get; set; }

        public virtual ICollection<Activity> Activity { get; set; }
        public virtual ICollection<UserHasTarget> UserHasTarget { get; set; }
    }
}