// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SportActivityAPI.Repository.Models
{
    public partial class Logedusers
    {
        public int Id { get; set; }
        public int? Logtime { get; set; }
    }
}