// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SportActivityAPI.Repository.Models
{
    public partial class UserHasTarget
    {
        public int UserId { get; set; }
        public int ActivityId { get; set; }
        public DateOnly? Date { get; set; }
        public string Type { get; set; }

        public virtual Activity Activity { get; set; }
        public virtual User User { get; set; }
    }
}