// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SportActivityAPI.Repository.Models
{
    public partial class User
    {
        public User()
        {
            Activity = new HashSet<Activity>();
            UserHasActivity = new HashSet<UserHasActivity>();
            UserHasTarget = new HashSet<UserHasTarget>();
        }

        public int Id { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }

        public virtual ICollection<Activity> Activity { get; set; }
        public virtual ICollection<UserHasActivity> UserHasActivity { get; set; }
        public virtual ICollection<UserHasTarget> UserHasTarget { get; set; }
    }
}