// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SportActivityAPI.Repository.Models
{
    public partial class UserHasActivity
    {
        public int UserId { get; set; }
        public int ActivityId { get; set; }

        public virtual User User { get; set; }
    }
}