// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SportActivityAPI.Repository.Models
{
    public partial class UserHasTarget
    {
        public int UserId { get; set; }
        public int ActivityTypeId { get; set; }
        public DateOnly DateActivity { get; set; }
        public string Type { get; set; }
        public int? Count { get; set; }
        public int? Target { get; set; }

        public virtual Activitytype ActivityType { get; set; }
        public virtual User User { get; set; }
    }
}